# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      ANDROID_HOME: /usr/local/android-sdk-linux
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
      
    dependencies:
        pre:
            # Remove any leftover lock from previous builds
            - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

            # Make sure we have the sdkmanager available, and update the Android SDK tools if not
            - if [ ! -e $ANDROID_HOME/tools/bin/sdkmanager ]; then echo y | android update sdk --no-ui --all --filter tools; fi
        
            # Pre-accept Android SDK components licenses
            - mkdir "$ANDROID_HOME/licenses" || true
            - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"

            # Install all the required SDK components
            - $ANDROID_HOME/tools/bin/sdkmanager --verbose "platform-tools" "build-tools;"$ANDROID_BUILD_TOOLS "extras;google;m2repository"
    

    cache_directories:
            - /usr/local/android-sdk-linux/platforms/android-25
            - /usr/local/android-sdk-linux/build-tools/25.0.2
            - /usr/local/android-sdk-linux/extras/android/m2repository
    
    steps:
    
    dependencies:
      -pre:
            - ( sleep 5 && while [ 1 ]; do sleep 1; echo y; done ) | android update sdk --no-ui --all --filter "tools,android-25,build-tools-25.0.2,platform-tools,extra-google-m2repository,extra-android-m2repository,extra-android-support,extra-google-google_play_services"
            
      -cache_directories:
            - /usr/local/android-sdk-linux/platforms/android-25
            - /usr/local/android-sdk-linux/build-tools/25.0.2
            - /usr/local/android-sdk-linux/extras/android/m2repository
            
      - checkout:
          post:  
            - cp -r licenses/. /usr/local/android-sdk-linux/licenses
            - ls /usr/local/android-sdk-linux/licenses

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
            
      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "build.gradle" }}
        
      # run tests!
      - run: gradle test



