# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
      
    dependencies:
        pre:
            # Android SDK Platform 24
            - if [ ! -d "/usr/local/android-sdk-linux/platforms/android-26" ]; then echo y | android update sdk --no-ui --all --filter "android-26"; fi
            # Android SDK Build-tools, revision 24.0.1
            - if [ ! -d "/usr/local/android-sdk-linux/build-tools/26.0.1" ]; then echo y | android update sdk --no-ui --all --filter "build-tools-26.0.1"; fi
            # Android Support Repository, revision 35 / Local Maven repository for Support Libraries
            - if [ ! -d "/usr/local/android-sdk-linux/extras/android/m2repository/com/android/support/design/26.1.0" ]; then echo y | android update sdk --no-ui --all --filter "extra-android-m2repository"; fi
    

    cache_directories:
            - /usr/local/android-sdk-linux/platforms/android-26
            - /usr/local/android-sdk-linux/build-tools/26.0.1
            - /usr/local/android-sdk-linux/extras/android/m2repository
    
    steps:
      - checkout:
          post:  
            - cp -r licenses/. $ANDROID_HOME/licenses
            - ks $ANDROID_HOME/licenses

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
            
      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "build.gradle" }}
        
      # run tests!
      - run: gradle test



